# 因为使用的hexo是通过npm安装的，这就要求nodejs环境
language: node_js
# 防止低版本会报错
node_js: stable
branches:
  only:
    - master
# 安装hexo以及运行hexo需要的一些node modules
# before _install:

install:
  - npm install
# 指定构建时的shell命令
script:
  - npm install es-lint
  - npm run lint
# 指定构建步骤成功后的执行动作
# after_success:
  
# 定于一些环境变量，这些会通过export的方式供当前shell引用
# env:
